currency_api_url: 	https://v6.exchangerate-api.com/v6/1d40c79e54dd9bde719c2bb0/latest/USD
grpc_port: ":8888"
http_port: ":8889"
connectDB: "host=db port=5432 user=pinchik password=qwerty1 dbname=postgres sslmode=disable"
jwt_token: "secret-key"
