// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: currency_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentRateRequest) Reset() {
	*x = GetCurrentRateRequest{}
	mi := &file_currency_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentRateRequest) ProtoMessage() {}

func (x *GetCurrentRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentRateRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentRateRequest) Descriptor() ([]byte, []int) {
	return file_currency_service_proto_rawDescGZIP(), []int{0}
}

type GetCurrentRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentRateResponse) Reset() {
	*x = GetCurrentRateResponse{}
	mi := &file_currency_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentRateResponse) ProtoMessage() {}

func (x *GetCurrentRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentRateResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentRateResponse) Descriptor() ([]byte, []int) {
	return file_currency_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentRateResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetCurrentRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type GetHistoryRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRateRequest) Reset() {
	*x = GetHistoryRateRequest{}
	mi := &file_currency_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRateRequest) ProtoMessage() {}

func (x *GetHistoryRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRateRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRateRequest) Descriptor() ([]byte, []int) {
	return file_currency_service_proto_rawDescGZIP(), []int{2}
}

type GetHistoryRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       map[string]float64     `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRateResponse) Reset() {
	*x = GetHistoryRateResponse{}
	mi := &file_currency_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRateResponse) ProtoMessage() {}

func (x *GetHistoryRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRateResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryRateResponse) Descriptor() ([]byte, []int) {
	return file_currency_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryRateResponse) GetHistory() map[string]float64 {
	if x != nil {
		return x.History
	}
	return nil
}

var File_currency_service_proto protoreflect.FileDescriptor

const file_currency_service_proto_rawDesc = "" +
	"\n" +
	"\x16currency_service.proto\x12\bcurrency\"\x17\n" +
	"\x15GetCurrentRateRequest\"@\n" +
	"\x16GetCurrentRateResponse\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\"\x17\n" +
	"\x15GetHistoryRateRequest\"\x9d\x01\n" +
	"\x16GetHistoryRateResponse\x12G\n" +
	"\ahistory\x18\x01 \x03(\v2-.currency.GetHistoryRateResponse.HistoryEntryR\ahistory\x1a:\n" +
	"\fHistoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012\xbb\x01\n" +
	"\x0fCurrencyService\x12S\n" +
	"\x0eGetCurrentRate\x12\x1f.currency.GetCurrentRateRequest\x1a .currency.GetCurrentRateResponse\x12S\n" +
	"\x0eGetHistoryRate\x12\x1f.currency.GetHistoryRateRequest\x1a .currency.GetHistoryRateResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_currency_service_proto_rawDescOnce sync.Once
	file_currency_service_proto_rawDescData []byte
)

func file_currency_service_proto_rawDescGZIP() []byte {
	file_currency_service_proto_rawDescOnce.Do(func() {
		file_currency_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_currency_service_proto_rawDesc), len(file_currency_service_proto_rawDesc)))
	})
	return file_currency_service_proto_rawDescData
}

var file_currency_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_currency_service_proto_goTypes = []any{
	(*GetCurrentRateRequest)(nil),  // 0: currency.GetCurrentRateRequest
	(*GetCurrentRateResponse)(nil), // 1: currency.GetCurrentRateResponse
	(*GetHistoryRateRequest)(nil),  // 2: currency.GetHistoryRateRequest
	(*GetHistoryRateResponse)(nil), // 3: currency.GetHistoryRateResponse
	nil,                            // 4: currency.GetHistoryRateResponse.HistoryEntry
}
var file_currency_service_proto_depIdxs = []int32{
	4, // 0: currency.GetHistoryRateResponse.history:type_name -> currency.GetHistoryRateResponse.HistoryEntry
	0, // 1: currency.CurrencyService.GetCurrentRate:input_type -> currency.GetCurrentRateRequest
	2, // 2: currency.CurrencyService.GetHistoryRate:input_type -> currency.GetHistoryRateRequest
	1, // 3: currency.CurrencyService.GetCurrentRate:output_type -> currency.GetCurrentRateResponse
	3, // 4: currency.CurrencyService.GetHistoryRate:output_type -> currency.GetHistoryRateResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_currency_service_proto_init() }
func file_currency_service_proto_init() {
	if File_currency_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_currency_service_proto_rawDesc), len(file_currency_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_service_proto_goTypes,
		DependencyIndexes: file_currency_service_proto_depIdxs,
		MessageInfos:      file_currency_service_proto_msgTypes,
	}.Build()
	File_currency_service_proto = out.File
	file_currency_service_proto_goTypes = nil
	file_currency_service_proto_depIdxs = nil
}
