name: Deploy to server
on:
  push:
    branches: [main, yoda]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/app/ExchangeDaily
            
            # Чистка
            docker compose down --volumes --rmi local
            pkill -9 -u postgres -f mysql || true
            rm -rf /tmp/mysql*
            
            git pull origin ${{ github.ref_name }}
            docker compose up -d --build --force-recreate
            docker system prune -f
            
            # Ожидание готовности
            sleep 15
            docker logs currency_service --tail 10

          
